version: "3.8"
services:
  database:
    image: postgres
    container_name: database_mvc
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
    ports:
      - 5432:5432
    volumes:
      - dbmvc:/data/postgres
  app:
    build: .
    container_name: express-mvc
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    depends_on:
      - database
    links:
      - database
volumes:
  dbmvc:
    driver: local